### ISSUE TITLE
feat: throwing runner

### ISSUE THREAD

**Issue by norskeld** [norskeld/sigma#54]
Add `tryRun` helper, that will, unlike `run`, throw in case of failure.

**Comment by TheFedaikin** [comment]
Should this be done via custom error that extends `Error`? I assume yes, because just throwing the `Failure` looks a little incomplete as a solution.

**Comment by norskeld** [comment]
> Should this be done via custom error that extends `Error`?
> Should this be imported to outside world, so they can check it with `instanceof`?

Yes and yes.
