### ISSUE TITLE
Postinstall fails on 3.6.3

### ISSUE THREAD

**Issue by gilbert** [norskeld/sigma#80]
### Describe the bug
```
npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nrsk/sigma@3.6.3',
npm WARN EBADENGINE   required: { node: '>=18.16.0 <=20' },
npm WARN EBADENGINE   current: { node: 'v18.15.0', npm: '9.5.0' }
npm WARN EBADENGINE }
npm ERR! code 1
npm ERR! path /Users/redacted/project/node_modules/@nrsk/sigma
npm ERR! command failed
npm ERR! command sh -c npm run install:benchmarks && npm run install:docs
npm ERR! > @nrsk/sigma@3.6.3 install:benchmarks
npm ERR! > cd benchmarks && npm i
npm ERR! sh: line 0: cd: benchmarks: No such file or directory
```

### Repro steps
Install 3.6.3 locally. I originally discovered the bug on trying to deploy to [render](https://render.com) since it caught the latest version due to my package.json having `^3.6.2` for sigma.

### System information
- macOS Ventura 13.2.1
- Shell: zsh 5.8.1

**Comment by norskeld** [comment]
This issue has been resolved in version [3.6.4](https://github.com/norskeld/sigma/releases/tag/v3.6.4).
