### ISSUE TITLE
defer() should error?

### ISSUE THREAD

**Issue by mindplay-dk** [norskeld/sigma#84]
Just wondering, I noticed this:

https://github.com/norskeld/sigma/blob/0d967375e7cf8f98bd9550e76f126fdaf648fa3e/src/parsers/defer.ts#L72-L77

I'm not sure this makes sense as a *parser* error?

It's not that parsing failed - it's that there is something wrong with your code.

So I think maybe it would be more appropriate to throw an error here?

You might have had some sort of reason for this - it looks a little off to me, so I figured I'd ask. 🙂

**Comment by norskeld** [comment]
Totally makes sense. I thought about making it throw an error, but forgot about that. I'd appreciate a PR!
