### ISSUE TITLE
Docs: `run` and `tryRun` aren't parsers

### ISSUE THREAD

**Issue by mindplay-dk** [norskeld/sigma#89]
I had trouble finding the `run` and `tryRun` functions, which are located in the "Parsers" section.

I would suggest adding a "Core" section at the top of the menu, and document the core functions of the library API there.

Probably moving the code itself into a "core" folder would make sense as well?

Let me know if you'd like a PR.

**Comment by norskeld** [comment]
You are right, this is confusing. I'm okay with moving `run` and `tryRun` into `core` folder and adding a section in the docs. I would move `defer` there as well. PR would be great, thanks!

P.S. I'll check other issues out and reply later, unfortunately day job and life stuff leave little to no time for pet projects.
